sotheme: jekyll-theme-minimal
title: VALÉRIE VALLI Personal Trainer
description: Specialista Preparazione Fisica & Resistenza, 
             
             Nutrizione Sportiva e Allenamenti Personalizzati
show_downloads: False
navigation:
  - title: Home
    url: /
  - title: Servizi
    url: services
  - title: Il mio percorso
    url : about
  - title: Contatto
    url: contact
  - title: Example
    url: example
