sotheme: jekyll-theme-minimal
title: VALÉRIE VALLI Personal Trainer
description: Website for her activity
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
  - title: Servizi
    url: services
  - title: Il mio percorso
    url : about
  - title: Contatto
    url: contact
